Adding the possiblity to change the log level
rock-core/tools-apaka pull request #9
Opened 2022-07-20 10:13 UTC by JustM3dium

Hallo @2maz kannst du dir den PR anschauen und mergen, wenn dieser gut ist. Ich hatte mit Dennis besprochen, dass die Standardausgabe von Apaka zu viele Informationen ausgegeben hat, dieses ist nun nicht mehr der Fall.

2022-07-20 21:44 UTC, 2maz requested changes
When you have applied the changes, feel free to merge - I am likely unavailable next two weeks.

2022-07-20 21:44 UTC, 2maz commented on lib/apaka/cli/base.rb
> +                ENV['APAKALOGLEVEL'] = 'warn'
I would prefer  to use APAKA_LOG_LEVEL, similar to BASE_LOG_LEVEL

2022-07-20 21:44 UTC, 2maz commented on lib/apaka/packaging/target_platform.rb
>          extend Logger::Root("Packaging", Logger::INFO)
Looks like you missed to remove that one.

2022-08-03 09:22 UTC, JustM3dium reviewed
Adding the requested changes.

2022-08-03 09:23 UTC, merged